import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const names = [
  'dragonite', 'rillaboom', 'volcarona', 'gengar', 'incineroar',
  'bulbasaur', 'charmander', 'squirtle', 'pikachu',
];
const signature = Buffer.from('89504e470d0a1a0a', 'hex');

const lines = [
  '// Generated by npm run prepare:sprites from the tracked PokeAPI PNG files.',
  'export const SPRITES = Object.freeze({',
];

for (const name of names) {
  const bytes = await readFile(path.join(root, 'assets', 'pokemon', `${name}.png`));
  if (!bytes.subarray(0, 8).equals(signature) || bytes.readUInt32BE(16) !== 96 || bytes.readUInt32BE(20) !== 96) {
    throw new Error(`${name}.png must be a 96x96 PNG`);
  }
  lines.push(`  ${name}: 'data:image/png;base64,${bytes.toString('base64')}',`);
}

lines.push('});', '');
await writeFile(path.join(root, 'src', 'sprites.generated.js'), lines.join('\n'));
